<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261008022541 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Voto único por participante e edição, com abertura, resultado e encerramento preservados.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE vote (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, presentation_id INT NOT NULL, voter_id INT NOT NULL, candidate_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_vote_presentation_voter ON vote (presentation_id, voter_id)');
        $this->addSql('CREATE INDEX IDX_5A108564AB627E8B ON vote (presentation_id)');
        $this->addSql('CREATE INDEX IDX_5A108564EBB4B8AD ON vote (voter_id)');
        $this->addSql('CREATE INDEX IDX_5A10856491BD8781 ON vote (candidate_id)');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564AB627E8B FOREIGN KEY (presentation_id) REFERENCES presentation (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A108564EBB4B8AD FOREIGN KEY (voter_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE vote ADD CONSTRAINT FK_5A10856491BD8781 FOREIGN KEY (candidate_id) REFERENCES app_user (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE presentation ADD voting_opened_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE presentation ADD closed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL');
        $this->addSql('ALTER TABLE presentation ADD ballot JSON DEFAULT NULL');
        $this->addSql('ALTER TABLE presentation ADD result JSON DEFAULT NULL');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564AB627E8B');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A108564EBB4B8AD');
        $this->addSql('ALTER TABLE vote DROP CONSTRAINT FK_5A10856491BD8781');
        $this->addSql('DROP TABLE vote');
        $this->addSql('ALTER TABLE presentation DROP voting_opened_at');
        $this->addSql('ALTER TABLE presentation DROP closed_at');
        $this->addSql('ALTER TABLE presentation DROP ballot');
        $this->addSql('ALTER TABLE presentation DROP result');
    }
}
