<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261006230302 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Contribuições com foto e texto, únicas por usuário e sexta-feira.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE submission (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, text TEXT NOT NULL, photo_filename VARCHAR(64) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, friday DATE NOT NULL, author_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_submission_author_friday ON submission (author_id, friday)');
        $this->addSql('CREATE INDEX IDX_DB055AF3F675F31B ON submission (author_id)');
        $this->addSql('ALTER TABLE submission ADD CONSTRAINT FK_DB055AF3F675F31B FOREIGN KEY (author_id) REFERENCES app_user (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE submission DROP CONSTRAINT FK_DB055AF3F675F31B');
        $this->addSql('DROP TABLE submission');
    }
}
