<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261007012526 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Apresentações por sexta-feira, com ordem sorteada e posição compartilhada.';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE presentation (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, position INT NOT NULL, friday DATE NOT NULL, submission_order JSON NOT NULL, started_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, started_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX uniq_presentation_friday ON presentation (friday)');
        $this->addSql('CREATE INDEX IDX_9B66E8939740C9D5 ON presentation (started_by_id)');
        $this->addSql('ALTER TABLE presentation ADD CONSTRAINT FK_9B66E8939740C9D5 FOREIGN KEY (started_by_id) REFERENCES app_user (id) ON DELETE SET NULL NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE presentation DROP CONSTRAINT FK_9B66E8939740C9D5');
        $this->addSql('DROP TABLE presentation');
    }
}
